#ifndef NCOMPUTERINFO_GLOBAL_H
#define NCOMPUTERINFO_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(NCOMPUTERINFO_LIBRARY)
#  define NCOMPUTERINFOSHARED_EXPORT Q_DECL_EXPORT
#else
#  define NCOMPUTERINFOSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // NCOMPUTERINFO_GLOBAL_H
